// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpqyRNLU7OcyEHor_dLyR_2g7oyDwj2Xc',
    appId: '1:983309681927:web:84b30d5d9fcfce403071a2',
    messagingSenderId: '983309681927',
    projectId: 'vsf-consumer',
    authDomain: 'vsf-consumer.firebaseapp.com',
    storageBucket: 'vsf-consumer.firebasestorage.app',
    measurementId: 'G-BFX0BBN6H4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAte_IOYCs0BfHmXzQCwfvGZYEQm-oXfP4',
    appId: '1:983309681927:android:73bb50c11593d7ef3071a2',
    messagingSenderId: '983309681927',
    projectId: 'vsf-consumer',
    storageBucket: 'vsf-consumer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM5aI6qKACoM6vhkekgKPM5OZVBqi8cMM',
    appId: '1:983309681927:ios:05f9f6989be12d343071a2',
    messagingSenderId: '983309681927',
    projectId: 'vsf-consumer',
    storageBucket: 'vsf-consumer.firebasestorage.app',
    iosBundleId: 'com.example.vsfConsumer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM5aI6qKACoM6vhkekgKPM5OZVBqi8cMM',
    appId: '1:983309681927:ios:05f9f6989be12d343071a2',
    messagingSenderId: '983309681927',
    projectId: 'vsf-consumer',
    storageBucket: 'vsf-consumer.firebasestorage.app',
    iosBundleId: 'com.example.vsfConsumer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpqyRNLU7OcyEHor_dLyR_2g7oyDwj2Xc',
    appId: '1:983309681927:web:847ca6a7b47552dd3071a2',
    messagingSenderId: '983309681927',
    projectId: 'vsf-consumer',
    authDomain: 'vsf-consumer.firebaseapp.com',
    storageBucket: 'vsf-consumer.firebasestorage.app',
    measurementId: 'G-FT9DV2SYNW',
  );
}
